// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://esycmohgumryeqteiwla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzeWNtb2hndW1yeWVxdGVpd2xhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ3NTYyMDksImV4cCI6MjA5MDMzMjIwOX0.Qa6683q4MwKzWEMGgEB-fQG8jiSJw3xoZp4b6GyaAf8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});